# Generated by Django 3.0 on 2020-02-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplieremployee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieremployee',
            name='services',
        ),
    ]
