version: '3.7'

services:
  web:
    build:
      context: ./zapisator
      dockerfile: Dockerfile
    volumes:
      - ./zapisator/:/web/zapisator/core
    ports:
      - 8000:8000
    env_file:
      - env/web.env
    depends_on:
      - db
      - mailhog
#    restart: always

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "54320"
    ports:
      - 54320:5432
    env_file:
      - env/database.env
#    restart: always

  mailhog:
    image: mailhog/mailhog
    expose:
      - 1025
      - 8025
    #restart: always
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  postgres_data:
    driver: local