# Generated by Django 3.0 on 2020-02-03 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanExecutor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('executor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='executors.Executor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
