# Generated by Django 3.0 on 2020-02-03 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0002_supplieremployee'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='supplier_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.SupplierEmployee'),
        ),
        migrations.AddField(
            model_name='lunchbreak',
            name='schedule',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='lunch_breaks', to='schedules.Schedule'),
        ),
    ]
