# Generated by Django 3.0 on 2020-02-03 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('entries', '0001_initial'),
        ('clients', '0001_initial'),
        ('executors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='clients.Client'),
        ),
        migrations.AddField(
            model_name='entry',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='executors.Executor'),
        ),
        migrations.AddField(
            model_name='entry',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='services.Service'),
        ),
    ]
