# Generated by Django 3.0.3 on 2020-02-29 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('entries', '0002_auto_20200203_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='clients.Client'),
        ),
    ]
